### ISSUE TITLE
Framework website only works on Chrome based browsers

### ISSUE THREAD

**Issue by soapdog** [Banou26/ozjs#1]
The site https://js.ozapp.io only works on Chrome based browsers due to its usage of `attachShadow` which is not implemented in other engines. It would be great if the page for a web framework worked on all major browsers.

Screenshot from Firefox:

![firefox nightly 2018-01-23 10 42 13](https://user-images.githubusercontent.com/23247/35276294-17e9794e-002a-11e8-9d45-addea2aedd0d.png)

**Comment by Banou26** [comment]
Can you tell me your firefox version ? This shouldn't be a problem since i'm using https://github.com/webcomponents/webcomponentsjs for browsers that doesn't support ESM(that should include firefox)
Aside from that i'm currently working on a css module to recreate a similar shadow dom experience on ozjs for browsers that doesn't support it

**Comment by ThePythonDoge** [comment]
Fixed?

**Comment by Banou26** [comment]
Fixed for what ? Firefox nightly or another browser ?

**Comment by soapdog** [comment]
@Banou26 this is firefox nightly 60, it is failing on `attachShadow` for me.

**Comment by Banou26** [comment]
I'm closing this one since Firefox nightly(and soon normal Firefox) now supports the shadowDOM
